- advanced/fanin.go
Add an example for the fanIn pattern, which merges multiple channels into one.
I have extensively commented the code, as much as it looks a little ugly.
> add fanIn pattern

- beginner/RoundRobinSchedulingAlgorithm.go
A round-robin tournament scheduling algorithm.
> Arrays and loops.

- beginner/http.go
- beginner/shell.go
> Added some more examples

- advanced/functionmain.go
If you want to call a main function inside the main function itself, you should use labels and you should not call main function!
> Golang with labels

- beginner/Sorting in Go
> Create Sorting in Go

- beginner/deleteFromSlice.go
- beginner/functionvariadic.go
- test.sh
Add variadic function example
Add delete from slice example
> Added some examples

- beginner/fibonacci.go
> add fibonacci.go

- beginner/fizzbuzz.go
because no programming example set is complete without fizzbuzz
> added a fizzbuzz example

- beginner/foreach.go
- test.sh
#5 add foreach with range example
> add foreach example

- expert/parallel.go
The old code has lots of repeated lines and multiple channels. 
This approach allows for a dynamic amount of goroutines to be created.
#5
> refactor parallel for a more idiomatic approach

- advanced/bcrypt.go
- readme.md
- add example to create hash string in bcrypt
- also add example to compare whether the hashed string is one of plain string hash version
> add example hash string using bcrypt algorithm

- beginner/environment_var.go
Added file example for set and load environment variables
> Add env variables example

- beginner/hashing.go
I added an additional way to create hashes in the hashing example.
> Add additional way to create hashes

- expert/scanvalue.go
This also provides an example on how to encrypt and decrypt database
values transparently.
> Add example of Scan and Value interfaces for DB

- beginner/http.go
Thank you for this all examples. Great job!
But there was a small bug with importing http package. Another problem was with http.Get, because it returns 2 values not 3.
> Fix beginner http example

- advanced/json_bench/main_test.go
- readme.md
- test.sh
add benchmarking example with use case benchmarking Go JSON standard library running marshal and unmarshal data
> add benchmarking example

- beginner/file.go
maybe adding more commonly-used file operations in the future, like safe delete, truncate write etc.
> feat: add file operations example

- advanced/bcrypt.go
- advanced/in_array.go
Every exported function in a program should have a doc comment. The first sentence should be a summary that starts with the name being declared.
From [effective go](https://golang.org/doc/effective_go.html#commentary).
I generated this with [CodeLingo](https://codelingo.io) and I'm keen to get some feedback, *but this is automated so feel free to close it and just say **`opt out`** to opt out of future CodeLingo outreach PRs.*
> Fix function comments based on best practices from Effective Go

- advanced/command_line_arguments.go
- readme.md
Pull request for Command Line Arguments example.
Please review and merge.
> Command Line Arguments Example

- beginner/slice.go
Make and Append operation in slice beginner program (Close #55)
> Make and Append operation

- advanced/XMLparser.go
Added example for XML parsing with golang
> Added XML parser with Golang

- advanced/binary_search.go
Simple implementation of binary search in go
> Added binary search

- advanced/microservice_example/Dockerfile
- advanced/microservice_example/README.md
- advanced/microservice_example/main/main.go
- Created a simple microservice and containerized the microservice using Dockerfile
- Added README file for the same
> Containerized Microservice Example

- advanced/semaphore.go
Can you please add the hacktoberfest-accepted tag?
Thank you.
> Add concurrent execution limit example.

- beginner/differ.go
> differ.go is added
